#include <iostream>
#include <random>
using namespace std;

int main() {

	cout << "-------------- Welcome to the number guessing game --------------" << endl;
		

	int random = 1 + (rand() % 10);
	int guessedNumber;
	int guesses = 0;
	cout << "Guess a number between 1-10 generated by the computer ... " << endl;


	do {
		cin >> guessedNumber;
		if (guessedNumber < random) {
			cout << "Guess a bigger number :) " << endl;
			guesses++;
		}
		else if (guessedNumber > random) {
			cout << "Guess a smaller number :)" << endl;
			guesses++;
		}
	} while (random != guessedNumber);

	if (random == guessedNumber) {
		cout << "Hurray! You guessed the number " << endl
			<< "-> Your number : " << guessedNumber << endl
			<< "-> Computer's number : " << random << endl
			<< "Number of guesses : " << guesses;
	}

	return 0;
}